name: Bug Report
description: Report a bug in AI models, code, or documentation
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component has the bug?
      options:
        - AI Model/Algorithm
        - Data Processing Pipeline
        - Evaluation Scripts
        - Documentation
        - API/Interface
        - Deployment/Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load dataset...
        2. Run model training...
        3. Evaluate on test set...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if applicable
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, Windows 10, macOS 12]
        - Python version: [e.g., 3.8.10]
        - PyTorch/TensorFlow version: [e.g., PyTorch 1.12.0]
        - CUDA version (if applicable): [e.g., 11.6]
        - GPU: [e.g., NVIDIA RTX 3080]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots or error logs